CONFIG += no_fixpath
QT = core gui qml widgets
CONFIG += no_fixpath
QT = core gui qml widgets
CONFIG += no_fixpath
QT = core gui qml widgets
CONFIG += no_fixpath
QT = core gui qml widgets
CONFIG += no_fixpath
QT = core gui qml widgets
CONFIG += no_fixpath
QT = core gui qml widgets
CONFIG += no_fixpath
QT = core gui qml widgets
CONFIG += no_fixpath
QT = core gui qml widgets
CONFIG += no_fixpath
QT = core gui qml widgets
CONFIG += no_fixpath
QT = core gui qml widgets
CONFIG += no_fixpath
QT = core gui qml widgets
CONFIG += no_fixpath
QT = core gui qml widgets
